job('Sample maven project') {
    description('Sample maven project job generated by Job DSL plugin on ${new Date()}')
    scm {
        git('https://github.com/ManjotSingh531/stateful-java-web-app.git', 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'pom.xml')
    }
    publishers {
        archiveArtifacts('**/*.jar')
    }
}
